language: julia

os:
  - linux
  - osx

branches:
  only:
  - master

julia:
  - 0.6.4
  - 1.1

matrix:
  allow_failures:
    - julia: 0.6.4

notifications:
  email: false

install:
  - if [[ "$TRAVIS_JULIA_VERSION" != "0.6.4" ]]; then
      julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/cvdlab/LinearAlgebraicRepresentation.jl"))';
      julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/eOnofri04/AlphaStructures.jl"))';
    fi

after_success:
  - echo "$TRAVIS_JULIA_VERSION"
  - if [[ "$TRAVIS_JULIA_VERSION" == "0.6.4" ]]; then
      julia -e 'cd(Pkg.dir("PointClouds")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())';
      cd $TRAVIS_BUILD_DIR && julia -e 'Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';
    else
      julia -e 'using Pkg; cd(Pkg.dir("PointClouds")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())';
      cd $TRAVIS_BUILD_DIR && julia -e 'using Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';
    fi

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/build
  on:
    branch: master
